In [1]:
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
database= ('../DATA/database.sqlite')

## Make connection

In [5]:
conn= sqlite3.connect(database)

In [6]:
conn

## Look at the tables

In [10]:
tables=pd.read_sql('''SELECT *
                        FROM sqlite_master
                        WHERE type="table"''',conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Country,Country,2,"CREATE TABLE Country (\n CountryCode TEXT,\..."
1,table,CountryNotes,CountryNotes,186,CREATE TABLE CountryNotes (\n Countrycode T...
2,table,Series,Series,948,"CREATE TABLE Series (\n SeriesCode TEXT,\n ..."
3,table,Indicators,Indicators,4448,CREATE TABLE Indicators (\n CountryName TEX...
4,table,SeriesNotes,SeriesNotes,1317550,CREATE TABLE SeriesNotes (\n Seriescode TEX...
5,table,Footnotes,Footnotes,1317587,CREATE TABLE Footnotes (\n Countrycode TEXT...

### SELECT A COUNTRY

In [13]:
country=pd.read_sql('''SELECT *
                FROM country''',conn)
country

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011,2013,2006
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",,,2010,2013,2001
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,,East Asia & Pacific,Upper middle income,AS,...,,,2010,,,Yes,2007,,,
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,,Europe & Central Asia,High income: nonOECD,AD,...,,,2011. Population data compiled from administra...,,,Yes,,,2006,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,WBG,West Bank and Gaza,West Bank and Gaza,West Bank and Gaza,PS,Israeli new shekel,The new base year is 2004.,Middle East & North Africa,Lower middle income,GZ,...,Budgetary central government,Special Data Dissemination Standard (SDDS),2007,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011",,,2010,,2005
243,WLD,World,World,World,1W,,World aggregate.,,,1W,...,,,,,,,,,,
244,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Based on official government statistics and In...,Middle East & North Africa,Lower middle income,RY,...,Budgetary central government,General Data Dissemination System (GDDS),2004,"Demographic and Health Survey (DHS), 2013","Expenditure survey/budget survey (ES/BS), 2005",,,2009,2013,2005
245,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,The new base year is 2010. National accounts d...,Sub-Saharan Africa,Lower middle income,ZM,...,Budgetary central government,General Data Dissemination System (GDDS),2010,"Demographic and Health Survey (DHS), 2013/14","Integrated household survey (IHS), 2010",,2010. Population and Housing Census.,,2013,2002
246,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,Consolidated central government,General Data Dissemination System (GDDS),2012,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002

### SELECT LatestIndustrialData	greater than 2011

In [22]:
pd.read_sql('''SELECT Shortname AS country, LatestIndustrialData
                FROM country
                WHERE 'LatestIndustrialData' >"2011"''',conn)

                country LatestIndustrialData
0           Afghanistan
1               Albania                 2011
2               Algeria                 2010
3        American Samoa
4               Andorra
..                  ...                  ...
242  West Bank and Gaza                 2010
243               World
244               Yemen                 2009
245              Zambia
246            Zimbabwe

[247 rows x 2 columns]

### SELECT NEWZEALAND, REGIN, industrial data greater than 2009,latesttradedata

In [30]:
pd.read_sql('''SELECT Shortname AS country,
                    region,
                    latesttradedata,
                    latestindustrialdata
                FROM country
                WHERE shortname= "New Zealand" 
                AND latesttradedata>"2003" 
                AND latestindustrialdata>"2009"''',conn)

       country               Region  LatestTradeData  LatestIndustrialData
0  New Zealand  East Asia & Pacific             2013                  2010

In [33]:
pd.read_sql('''SELECT Shortname AS country,
                    region,
                    latesttradedata,
                    latestindustrialdata
                FROM country
                WHERE shortname= "New Zealand" 
                OR latesttradedata>"2013" 
                OR latestindustrialdata>"2009"''',conn)

,country,Region,LatestTradeData,LatestIndustrialData
0,Afghanistan,South Asia,2013,
1,Albania,Europe & Central Asia,2013,2011
2,Algeria,Middle East & North Africa,2013,2010
3,American Samoa,East Asia & Pacific,,
4,Andorra,Europe & Central Asia,2006,
...,...,...,...,...
209,Virgin Islands,Latin America & Caribbean,,
210,West Bank and Gaza,Middle East & North Africa,,2010
211,World,,,
212,Zambia,Sub-Saharan Africa,2013,
213,Zimbabwe,Sub-Saharan Africa,2013,

In [34]:
notes=pd.read_sql('''SELECT *
                FROM countrynotes''',conn)
notes

,Countrycode,Seriescode,Description
0,ABW,EG.EGY.PRIM.PP.KD,Sources: Estimated based on UN Energy Statisti...
1,ABW,EG.ELC.RNEW.ZS,Sources: UN Energy Statistics (2014)
2,ABW,EG.FEC.RNEW.ZS,Sources: UN Energy Statistics (2014)
3,ABW,SM.POP.NETM,Data sources : United Nations World Population...
4,ABW,SM.POP.TOTL,Estimates are derived from data on foreign-bor...
...,...,...,...
4852,ZWE,SP.DYN.LE00.IN,Derived using male and female life expectancy
4853,ZWE,SP.DYN.LE00.MA.IN,Data sources : United Nations World Population...
4854,ZWE,SP.DYN.TFRT.IN,Data sources : United Nations World Population...
4855,ZWE,SP.POP.GROW,Data sources: United Nations World Population ...
4856,ZWE,SP.POP.TOTL,Data sources : United Nations World Population...

JOIN COUNTry and  country notes

In [38]:
pd.read_sql('''SELECT *
                FROM country 
                JOIN countrynotes 
                ON country.Countrycode=countrynotes.Countrycode''',conn)

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData,Countrycode,Seriescode,Description
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,DT.DOD.DECT.CD,Long-term public and publicly guaranteed debt ...
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,EG.EGY.PRIM.PP.KD,Sources: Estimated based on UN Energy Statisti...
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,EG.ELC.RNEW.ZS,Sources: UN Energy Statistics (2014)
3,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,EG.FEC.RNEW.ZS,Sources: UN Energy Statistics (2014)
4,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,NE.CON.PRVT.PP.CD,Estimates are based on regression.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4851,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.DYN.LE00.IN,Derived using male and female life expectancy
4852,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.DYN.LE00.MA.IN,Data sources : United Nations World Population...
4853,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.DYN.TFRT.IN,Data sources : United Nations World Population...
4854,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.POP.GROW,Data sources: United Nations World Population ...
4855,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.POP.TOTL,Data sources : United Nations World Population...

In [39]:
series=pd.read_sql('''SELECT *
                FROM series''',conn)
series

,SeriesCode,Topic,IndicatorName,ShortDefinition,LongDefinition,UnitOfMeasure,Periodicity,BasePeriod,OtherNotes,AggregationMethod,LimitationsAndExceptions,NotesFromOriginalSource,GeneralComments,Source,StatisticalConceptAndMethodology,DevelopmentRelevance,RelatedSourceLinks,OtherWebLinks,RelatedIndicators,LicenseType
0,BN.KLT.DINV.CD,Economic Policy & Debt: Balance of payments: C...,"Foreign direct investment, net (BoP, current US$)",,Foreign direct investment are the net inflows ...,,Annual,,,,,,Note: Data are based on the sixth edition of t...,"International Monetary Fund, Balance of Paymen...",,,,,,Open
1,BX.KLT.DINV.WD.GD.ZS,Economic Policy & Debt: Balance of payments: C...,"Foreign direct investment, net inflows (% of GDP)",,Foreign direct investment are the net inflows ...,,Annual,,,Weighted average,FDI data do not give a complete picture of int...,,Note: Data starting from 2005 are based on the...,"International Monetary Fund, International Fin...",Data on equity flows are based on balance of p...,Private financial flows - equity and debt - ac...,,,,Open
2,BX.KLT.DINV.CD.WD,Economic Policy & Debt: Balance of payments: C...,"Foreign direct investment, net inflows (BoP, c...",,Foreign direct investment refers to direct inv...,,Annual,,,Sum,FDI data do not give a complete picture of int...,,Note: Data starting from 2005 are based on the...,"International Monetary Fund, Balance of Paymen...",Data on equity flows are based on balance of p...,Private financial flows - equity and debt - ac...,,,,Open
3,BM.KLT.DINV.GD.ZS,Economic Policy & Debt: Balance of payments: C...,"Foreign direct investment, net outflows (% of ...",,Foreign direct investment are the net inflows ...,,Annual,,,Weighted average,,,Note: Data are based on the sixth edition of t...,"International Monetary Fund, International Fin...",,,,,,Open
4,BN.TRF.KOGT.CD,Economic Policy & Debt: Balance of payments: C...,"Net capital account (BoP, current US$)",,Net capital account records acquisitions and d...,,Annual,,,,,,Note: Data are based on the sixth edition of t...,"International Monetary Fund, Balance of Paymen...",,,,,,Open
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,SL.UEM.1524.FE.NE.ZS,Social Protection & Labor: Unemployment,"Unemployment, youth female (% of female labor ...",,Youth unemployment refers to the share of the ...,,Annual,,,Weighted average,Data on youth unemployment are drawn from labo...,,"Data are based on labor force sample surveys, ...","International Labour Organization, Key Indicat...",The standard definition of unemployed persons ...,Youth unemployment is an important policy issu...,,,,Open
1341,SL.UEM.1524.MA.ZS,Social Protection & Labor: Unemployment,"Unemployment, youth male (% of male labor forc...",,Youth unemployment refers to the share of the ...,,Annual,,,Weighted average,There may be persons not currently in the labo...,,The unemployment rates presented here are the ...,"International Labour Organization, Key Indicat...",The standard definition of unemployed persons ...,Youth unemployment is an important policy issu...,,,,Open
1342,SL.UEM.1524.MA.NE.ZS,Social Protection & Labor: Unemployment,"Unemployment, youth male (% of male labor forc...",,Youth unemployment refers to the share of the ...,,Annual,,,Weighted average,Data on youth unemployment are drawn from labo...,,"Data are based on labor force sample surveys, ...","International Labour Organization, Key Indicat...",The standard definition of unemployed persons ...,Youth unemployment is an important policy issu...,,,,Open
1343,SL.UEM.1524.ZS,Social Protection & Labor: Unemployment,"Unemployment, youth total (% of total labor fo...",,Youth unemployment refers to the share of the ...,,Annual,,,Weighted average,There may be persons not currently in the labo...,,The unemployment rates presented here are the ...,"International Labour Organization, Key Indicat...",The standard definition of unemployed persons ...,Youth unemployment is an important policy issu...,,,,Open
1344,SL.UEM.1524.NE.ZS,Social Protection & Labor: Unemployment,"Unemployment, youth total (% of total labor fo...",,Youth unemployment refers to the share of the ...,,Annual,,,Weighted average,Data on youth unemployment are drawn from labo...,,"Data are based on labor force sample surveys, ...","International Labour Organization, Key Indicat...",The standard definition of unemployed persons ...,Youth unemployment is an important policy issu...,,,,Open

In [40]:
pd.read_sql('''SELECT *
                FROM country c
                JOIN countrynotes cn
                ON c.Countrycode=cn.Countrycode''',conn)

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData,Countrycode,Seriescode,Description
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,DT.DOD.DECT.CD,Long-term public and publicly guaranteed debt ...
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,EG.EGY.PRIM.PP.KD,Sources: Estimated based on UN Energy Statisti...
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,EG.ELC.RNEW.ZS,Sources: UN Energy Statistics (2014)
3,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,EG.FEC.RNEW.ZS,Sources: UN Energy Statistics (2014)
4,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000,AFG,NE.CON.PRVT.PP.CD,Estimates are based on regression.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4851,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.DYN.LE00.IN,Derived using male and female life expectancy
4852,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.DYN.LE00.MA.IN,Data sources : United Nations World Population...
4853,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.DYN.TFRT.IN,Data sources : United Nations World Population...
4854,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.POP.GROW,Data sources: United Nations World Population ...
4855,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011/12",,,,2013,2002,ZWE,SP.POP.TOTL,Data sources : United Nations World Population...